import OpenAI from "openai";
import type {
  ForecastResult,
  HkoWeatherSnapshot,
  MarketState
} from "@/types";

export async function generatePoeExplanation(params: {
  snapshot: HkoWeatherSnapshot;
  state: MarketState;
  forecast: Omit<ForecastResult, "aiExplanation">;
}) {
  const apiKey = process.env.POE_API_KEY;
  const model = process.env.POE_MODEL || "Claude-Sonnet-4.6";

  if (!apiKey) {
    return "AI explanation skipped: POE_API_KEY is not configured on the server.";
  }

  try {
    const client = new OpenAI({
      apiKey,
      baseURL: "https://api.poe.com/v1"
    });

    function getOutcomeMarketPrice(outcome: {
  marketPrice?: unknown;
  price?: unknown;
}) {
  if (typeof outcome.marketPrice === "number") {
    return outcome.marketPrice;
  }

  if (typeof outcome.price === "number") {
    return outcome.price;
  }

  return null;
}
    const marketVsModel = params.state.outcomes.map((outcome) => {
  const modelProbability =
    params.forecast.outcomeProbabilities?.find(
      (item) => item.name === outcome.name
    )?.probability ?? null;

  const marketProbability = getOutcomeMarketPrice(outcome);

  const edge =
    typeof modelProbability === "number" &&
    typeof marketProbability === "number"
      ? modelProbability - marketProbability
      : null;

  return {
    name: outcome.name,
    lower: outcome.lower,
    upper: outcome.upper,
    polymarketProbability: marketProbability,
    modelProbability,
    edge
  };
});
    const payload = {
      hkoCurrent: params.snapshot.current,
      hkoSinceMidnight: params.snapshot.sinceMidnight,
      hkoHourlyRainfall: params.snapshot.hourlyRainfall,
      hkoForecastFirstThreeDays: params.snapshot.forecast.days.slice(0, 3),
      marketState: params.state,
      modelForecast: {
        hktDate: params.forecast.hktDate,
        maxSoFarC: params.forecast.maxSoFarC,
        maxSoFarSource: params.forecast.maxSoFarSource,
        estimatedFinalMaxC: params.forecast.estimatedFinalMaxC,
        outcomeProbabilities: params.forecast.outcomeProbabilities,
        keyDrivers: params.forecast.keyDrivers,
        warnings: params.forecast.warnings
      }
    };

    const completion = await client.chat.completions.create({
      model,
      temperature: 0.2,
      max_tokens: 420,
      messages: [
        {
          role: "system",
          content:
  [
    "You are a Hong Kong weather prediction market analyst.",
    "You must clearly distinguish Polymarket market prices from the app's weather model probabilities.",
    "Never call model probabilities 'market odds' or 'market probabilities'.",
    "Use 'Polymarket 盤口 / 市場價格' only for marketPrice / clobMidpoint / yesAsk / noAsk.",
    "Use '模型概率' only for outcomeProbabilities generated by the forecast model.",
    "Edge means modelProbability minus Polymarket market probability.",
    "Do not claim final settlement. Final settlement depends on finalized official HKO data and market rules.",
    "Answer in Traditional Chinese with a Hong Kong Cantonese tone."
  ].join("\n")
        {
          role: "user",
          content: `請根據以下 JSON，用繁體中文加少少香港粵語語氣分析。

你必須分開以下三種數字：
1. Polymarket 盤口 / 市場價格：來自 outcome.marketPrice、clobMidpoint、yesAsk、noAsk。
2. 模型概率：來自 modelForecast.outcomeProbabilities。
3. Edge：模型概率 - Polymarket 盤口。

嚴禁把模型概率稱為「市場賠率」。
如果 25°C 的模型概率是 64%，但 Polymarket 只有 9%，你要寫：
「模型估 25°C 約64%，但 Polymarket 盤口約9%，edge 約+55%。」
不要寫：
「市場認為 25°C 約64%。」

請輸出：
1. Polymarket 盤口重點
2. 模型概率重點
3. 最大分歧 / edge
4. 天氣驅動因素
5. settlement / data risk

資料 JSON：
${JSON.stringify(payload, null, 2)}`
        }
      ]
    });

    const content = completion.choices[0]?.message?.content;

    if (typeof content === "string" && content.trim().length > 0) {
      return content.trim();
    }

    return "AI explanation returned empty content.";
  } catch (error) {
    console.error("Poe API error:", error);
    return "AI explanation temporarily failed. Please check POE_API_KEY, POE_MODEL, or Vercel function logs.";
  }
}
